export const CANVAS_WORLD_WIDTH = 1600;
export const CANVAS_WORLD_HEIGHT = 1000;

export const CANVAS_WORLD_CENTER_X = CANVAS_WORLD_WIDTH / 2;
export const CANVAS_WORLD_CENTER_Y = CANVAS_WORLD_HEIGHT / 2;

export const IMAGE_LAYER_DEFAULT_SIZE = 560;

export const DEFAULT_IMAGE_LAYER_PLACEMENT = {
  x: CANVAS_WORLD_CENTER_X - IMAGE_LAYER_DEFAULT_SIZE / 2,
  y: CANVAS_WORLD_CENTER_Y - IMAGE_LAYER_DEFAULT_SIZE / 2,
  width: IMAGE_LAYER_DEFAULT_SIZE,
  height: IMAGE_LAYER_DEFAULT_SIZE,
};
